### ISSUE TITLE
stack expects each tensor to be equal size, but got [39] at entry 0 and [43] at entry 1

### ISSUE THREAD

**Issue by wamaster** [aizpy/chatglm-finetune#1]
```cmd
Traceback (most recent call last):
  File "finetune.py", line 201, in <module>
    trainer.train()
  File "/home/hyhladmin/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/home/hyhladmin/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1872, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/hyhladmin/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/hyhladmin/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hyhladmin/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "finetune.py", line 148, in collate_fn
    'input_ids': torch.stack(input_ids),
RuntimeError: stack expects each tensor to be equal size, but got [39] at entry 0 and [43] at entry 1
```

**Comment by aizpy** [comment]
Support for multiple batches is not yet available.

**Comment by wamaster** [comment]
下载代码之后运行finetune.py直接抛出了这段错误，没有修改过batches的内容。

**Comment by aizpy** [comment]
如果是直接下载源码跑`finetune.py`的话，我这边测试过是没有问题的。不知道你是否有修改过其他东西？

**Comment by wamaster** [comment]
感谢您的答复，
我只修改了checkpoint的模型路径THUDM/chatglm-6b为chatglm-6b，其它未作修改。

**Comment by aizpy** [comment]
你是下载了最新版的模型到本地是吗？当前新版的模型是有针对多批次进行处理的，不知道是不是这个原因对训练造成了影响。你可以先指定`revision`来限定版本号，或者 git 到指定版本号的 commit。

**Comment by cywjava** [comment]
你只要改了qa.json里question的长度，或者改了per_device_train_batch_size=大于1，你就会得到这样的错误
张量大小不一致。

只能改 data_collator方法实现。。

**Comment by changyibiao** [comment]
@wamaster   You can try:
CUDA_VISIBLE_DEVICES=0 python  finetune.py

**Comment by Gunker** [comment]
> 感谢您的答复， 我只修改了checkpoint的模型路径THUDM/chatglm-6b为chatglm-6b，其它未作修改。

请问这个问题您解决了么？我也遇到同样的问题

**Comment by YangPei1993** [comment]
确实会报size不一致，我也遇到了

**Comment by PedroNeal** [comment]
> > 感谢您的答复， 我只修改了checkpoint的模型路径THUDM/chatglm-6b为chatglm-6b，其它未作修改。
> 
> 请问这个问题您解决了么？我也遇到同样的问题

请问解决了吗，我也遇到了这样的问题

**Comment by PedroNeal** [comment]
> 确实会报size不一致，我也遇到了

请问解决了吗，我也遇到了这样的问题

**Comment by PedroNeal** [comment]
> 你只要改了qa.json里question的长度，或者改了per_device_train_batch_size=大于1，你就会得到这样的错误 张量大小不一致。
> 
> 只能改 data_collator方法实现。。

请问您是怎么解决的

**Comment by PedroNeal** [comment]
> r_device_train_batch

用您的源码和数据都会有这个问题，问下是所用的包的版本的问题吗？
